import { ProductType } from 'src/types/product';

export const cardProductData: any[] = [
  {
    id: 1,
    name: 'Nấm đùi gà Green Kingdom 250gr',
    quantity: 56,
    sold: 52,
    isHot: true,
    isNew: false,
    rating: 3.5,
    image: '/images/assets/product-1.jpg',
    category: 'rau-cu',
    to: '/',
    desc: 'Vị ngọt tự nhiên, giàu dinh dưỡng. - Nấm chứa đạm tốt. Thay thế đạm động vật được tuy nhiên Nấm là nguồn năng lượng tối, nên ăn vừa phải, vì nấm gây trì trệ.',
    price: 31000,
    discount: 21,
  },
  {
    id: 2,
    name: 'Nấm hương tươi Green Kingdom',
    quantity: 112,
    sold: 26,
    isHot: false,
    isNew: false,
    rating: 4.5,
    image: '/images/assets/product-2.jpg',
    category: 'rau-cu',
    to: '/',
    desc: '👍 Vị ngọt tự nhiên, giàu dinh dưỡng. - Nấm chứa đạm tốt. Thay thế đạm động vật được tuy nhiên Nấm là nguồn năng lượng tối, nên ăn vừa phải, vì nấm gây trì trệ. - Nấm Green Kingdom đa dạng với các loại nấm ngon, được trồng và chăm sóc bởi các chuyên gia kinh nghiệm và nói không với các chất bảo',
    price: 69000,
  },
  {
    id: 3,
    name: 'Mọc heo An Mộc 1kg',
    quantity: 76,
    sold: 3,
    isHot: true,
    isNew: false,
    rating: 4.5,
    image: '/images/assets/product-3.png',
    category: 'thit-ca',
    to: '/',
    desc: '🌿 KHÔNG BIẾN ĐỔI GEN 🌿 KHÔNG SỬ DỤNG KHÁNG SINH 🌿 KHÔNG CHẤT TĂNG TRƯỞNG 🌿 KHÔNG',
    price: 95000,
  },
  {
    id: 4,
    name: 'Quả chà là khô hữu cơ Smart Organic 200Gr',
    quantity: 94,
    sold: 19,
    isHot: false,
    isNew: true,
    rating: 5,
    image: '/images/assets/product-4.jpg',
    category: 'do-kho',
    to: '/',
    desc: 'Chà là là loại đồ ăn vặt ngon và giàu dinh dưỡng. Chúng cực kỳ linh hoạt – có thể được thưởng thức ăn liền hoặc là một thành phần của...',
    price: 145000,
    discount: 19,
  },
  {
    id: 5,
    name: 'Hạt hạnh nhân hữu cơ Smart Organic 200Gr',
    quantity: 50,
    sold: 11,
    isHot: true,
    isNew: false,
    rating: 4.5,
    image: '/images/assets/product-5.jpg',
    category: 'do-kho',
    to: '/',
    desc: 'Hạnh nhân là một món ăn nhẹ dễ dàng, giàu chất dinh dưỡng mà bạn có thể thưởng thức vào giữa các bữa ăn hoặc thêm vào các món ăn khác...',
    price: 200000,
    discount: 7,
  },
  {
    id: 6,
    name: 'Sốt Mayorice hữu cơ không trứng 145g ProBios Organic Mayorice in Tube',
    quantity: 156,
    sold: 74,
    isHot: false,
    isNew: true,
    rating: 3,
    image: '/images/assets/product-6.jpg',
    category: 'do-kho',
    to: '/',
    desc: 'Chứng nhận hữu cơ Châu Âu Vegan Non GMO Gluten Free Thành phần: dầu hướng dương, nước, giấm táo, bột gạo 3,6%, xi-rô agave, muối biển, nước chanh, bột mù tạt, tinh bột ngô, guargum, xanthan gum, protein',
    price: 130000,
  },
  {
    id: 7,
    name: 'Cherry đỏ - size 9 1kg',
    quantity: 55,
    sold: 33,
    isHot: false,
    isNew: false,
    rating: 3.5,
    image: '/images/assets/product-7.jpg',
    category: 'trai-cay',
    to: '/',
    desc: 'Nhập khẩu đường máy bay (Air). Hàng đầu mùa rất tươi, cuốn xanh. Mọng nước, trái chín đậm vị, trái xanh cứng trái. Đầu mùa vị ngọt chua...',
    price: 0,
  },
  {
    id: 8,
    name: 'Tỏi tím Organic 200gr',
    quantity: 231,
    sold: 231,
    isHot: true,
    isNew: false,
    rating: 4.5,
    image: '/images/assets/product-8.png',
    category: 'rau-cu',
    to: '/',
    desc: 'Trong thành phần của tỏi có chứa nhiều chất kháng sinh allicin giúp chống lại các virút gây bệnh, tăng sức đề kháng cho cơ thể. Tinh dầu chiết xuất từ tỏi giàu glucogen và aliin, fitonxit có...',
    price: 41500,
  },
  {
    id: 9,
    name: 'Việt quất 125gr',
    quantity: 86,
    sold: 71,
    isHot: false,
    isNew: false,
    rating: 4.5,
    image: '/images/assets/product-9.jpg',
    category: 'trai-cay',
    to: '/',
    desc: 'Tiêu chuẩn chất lượng : Nhập Khẩu + Xuất xứ : Mỹ + Đặc điểm sản phẩm: Trái to vừa, vị ngọt thanh, ít calo. Thích hợp để làm sinh tố, sữa..',
    price: 129000,
    discount: 8,
  },
  {
    id: 10,
    name: 'Chân giò rút xương An Mộc 1kg',
    quantity: 43,
    sold: 14,
    isHot: false,
    isNew: false,
    rating: 1.5,
    image: '/images/assets/chan-gio-rut-xuong-heo-5a1e8c65-d03c-486f-b1b5-deb21855d635.jpg',
    category: 'thit-ca',
    to: '/',
    desc: '🌈Với quyết tâm thực hiện mô hình SẠCH TỪ TRANG TRẠI ĐẾN BÀN ĂN, thịt heo An Mộc luôn đảm bảo là thịt sạch tốt nhất cho sự lựa chọn của gia đình bạn. Là chuỗi trang trại...',
    price: 190000,
  },
  {
    id: 11,
    name: 'Táo Juliet Hữu Cơ',
    quantity: 54,
    sold: 11,
    isHot: true,
    isNew: false,
    rating: 4.5,
    image: '/images/assets/product-11.png',
    category: 'trai-cay',
    to: '/',
    desc: ' Dòng Táo hữu cơ của Miền Nam nước Pháp luôn được khách của Organic Mart đợi mong bởi ngoài yếu tố organic thì táo Juliet thật sự ngon giòn tan, ngọt lịm, rất cứng trái chứ không bị xốp bở',
    price: 139000,
  },
  {
    id: 12,
    name: 'Ba rọi nách An Mộc 1kg',
    quantity: 55,
    sold: 0,
    isHot: false,
    isNew: false,
    rating: 4.5,
    image: '/images/assets/product-12.jpg',
    category: 'thit-ca',
    to: '/',
    desc: 'Thịt heo An Mộc luôn đảm bảo là thịt sạch tốt nhất cho sự lựa chọn của gia đình bạn. Là chuỗi trang trại...',
    price: 210000,
    discount: 10,
  },
  {
    id: 13,
    name: 'Mọc heo An Mộc 1kg',
    quantity: 127,
    sold: 110,
    isHot: false,
    isNew: false,
    rating: 4.5,
    image: '/images/assets/product-13.png',
    category: 'thit-ca',
    to: '/',
    desc: '🌈Với quyết tâm thực hiện mô hình SẠCH TỪ TRANG TRẠI ĐẾN BÀN ĂN, thịt heo An Mộc luôn đảm bảo là thịt sạch tốt nhất cho sự lựa chọn của gia đình bạn. Là chuỗi trang trại...',
    price: 220000,
  },
  {
    id: 14,
    name: 'Kiwi vàng hữu cơ NewZeaLand',
    quantity: 12,
    sold: 0,
    isHot: true,
    isNew: false,
    rating: 4.5,
    image: '/images/assets/product-14.png',
    category: 'trai-cay',
    to: '/',
    desc: 'Những quả Kiwi Zespri Hữu Cơ được kiểm định bởi tổ chức BIO-GRO New Zealand. Kiwi Hữu Cơ được trồng và được chứng nhận theo tiêu chuẩn hữu cơ nghiêm ngặt nhất. Kiwi vàng Zespri Organic quả to,.',
    price: 209999,
    discount: 3,
  },
  {
    id: 15,
    name: 'Cải thảo dún Organic 300gr',
    quantity: 88,
    sold: 77,
    isHot: false,
    isNew: false,
    rating: 5,
    image: '/images/assets/product-10.jpg',
    category: 'rau-cu',
    to: '/',
    desc: 'Cải thảo có màu sắc khá giống với cải bắp, phần lá bao ngoài của màu xanh đậm, còn lá cuộn ở bên trong (gọi là lá non) có màu xanh nhạt, trong khi phần cuống lá có',
    price: 18000,
  },
  {
    id: 16,
    name: 'Vú Sữa Bắc Thảo',
    quantity: 90,
    sold: 10,
    isHot: true,
    isNew: false,
    rating: 4.5,
    image: '/images/assets/product-10.jpg',
    category: 'trai-cay',
    to: '/',
    desc: 'Ngọt xuất sắc cả nhà ah. Lâu rồi mới có vú sữa cho cả nhà mình, cơ mà nó ngon ngoài mong đợi của SHOP luôn ah. Khách nào chờ em ấy lâu rồi...',
    price: 82000,
  },
  {
    id: 17,
    name: 'Bột nghệ hữu cơ 150g Lumlum Organic Turmeric Powder',
    quantity: 42,
    sold: 21,
    isHot: false,
    isNew: false,
    rating: 4.5,
    image: '/images/assets/product-17.jpg',
    category: 'do-kho',
    to: '/',
    desc: 'Gia vị nấu ăn sạch và an toàn cho sức khỏe Tăng cường và cải thiện sức khỏe Thải độc da, giúp da sáng khỏe. Tăng cải thiện và tăng cường...',
    price: 229000,
    discount: 6,
  },
  {
    id: 18,
    name: 'Xương ống thịt An Mộc 1kg',
    quantity: 10,
    sold: 1,
    isHot: true,
    isNew: false,
    rating: 4.5,
    image: '/images/assets/product-18.jpg',
    category: 'thit-ca',
    to: '/',
    desc: 'Thịt heo An Mộc luôn đảm bảo là thịt sạch tốt nhất cho sự lựa chọn của gia đình bạn. Là chuỗi trang trại...',
    price: 180000,
  },
  {
    id: 19,
    name: 'Nho xanh Autumn Crisp 1kg',
    quantity: 12,
    sold: 0,
    isHot: false,
    isNew: false,
    rating: 4.5,
    image: '/images/assets/product-19.jpg',
    category: 'trai-cay',
    to: '/',
    desc: 'Nho xanh Autumn Crisp thịt giòn, ngọt, vỏ mỏng. Quả nho tròn, căng mọng nước. Bên ngoài mỗi quả nho được bao bọc bởi một lớp phấn tự nhiên mỏng giúp bảo vệ quả trong suốt quá trình từ...',
    price: 299000,
  },
  {
    id: 20,
    name: 'Bông cải xanh Organic 300g',
    quantity: 114,
    sold: 14,
    isHot: false,
    isNew: true,
    rating: 4.5,
    image: '/images/assets/product-20.png',
    category: 'rau-cu',
    to: '/',
    desc: 'Bông cải xanh có chứa chất hóa học được gọi là sulforaphane có thể kích thích sự sản sinh ra các enzyme chống ung thư. Bông cải xanh còn có tác dụng giúp xương chắc khỏe',
    price: 28000,
    discount: 20,
  },
  {
    id: 21,
    name: 'Mứt nam việt quất hữu cơ 320g Sottolestelle Organic Blueberrie Jam',
    quantity: 26,
    sold: 10,
    isHot: false,
    isNew: false,
    rating: 4.5,
    image: '/images/assets/product-21.png',
    category: 'do-kho',
    to: '/',
    desc: 'Xuất xứ : Sottolestelle –Ý Shelf Life : 36 tháng kể từ ngày sản xuất Chứng nhận hữu cơ Châu Âu Non GMO Vegan ...',
    price: 115000,
  },
  {
    id: 22,
    name: 'Mận An Phước',
    quantity: 241,
    sold: 141,
    isHot: false,
    isNew: false,
    rating: 4.5,
    image: '/images/assets/product-22.jpg',
    category: 'trai-cay',
    to: '/',
    desc: 'Mận An Phước có vỏ màu đỏ tím, có vân nhạt, tỏa mùi thơm nhẹ. Mận được chăm sóc, chọn lọc kỹ càng từng trái, đảm bảo thơm ngon đúng chuẩn.',
    price: 63000,
  },
  {
    id: 23,
    name: 'Cà chua picota organic 300g',
    quantity: 93,
    sold: 19,
    isHot: true,
    isNew: false,
    rating: 4.5,
    image: '/images/assets/product-23.png',
    category: 'rau-cu',
    to: '/',
    desc: 'Cà chua Picota là loại cà chua tròn nhỏ, giống Hà Lan, có hình dáng giống quả cherry màu đỏ rất bắt mắt, hương vị thơm ngon, thịt ngọt dày. Cũng giống như cà chua beef',
    price: 37000,
  },
  {
    id: 24,
    name: 'Kiwi vàng NewZealand 1kg',
    quantity: 65,
    sold: 56,
    isHot: false,
    isNew: true,
    rating: 4.5,
    image: '/images/assets/product-25.jpg',
    category: 'trai-cay',
    to: '/',
    desc: 'Kiwi của Newzealand ngon số 1 thế giới. Toàn bộ quy trình từ trồng, chăm bón đến thu, hái, vận chuyển đều được chính phủ Newzealand kiểm soát rất chặt chẽ để đảm bảo trái Kiwi Newzealand',
    price: 179000,
    discount: 10,
  },
  {
    id: 25,
    name: 'Siro Lá Phong Maple Syrup Hữu Cơ Radiant Code 250ml',
    quantity: 56,
    sold: 0,
    isHot: false,
    isNew: false,
    rating: 4.5,
    image: '/images/assets/product-25.jpg',
    category: 'do-kho',
    to: '/',
    desc: 'Đạt chứng nhận hữu cơ BioGro của New Zealand Non - GMO, không chất bảo quản Không pha tạp chất, hóa chất độc hại Nhập khẩu từ Malaysia An toàn khi sử dụng Siro Lá Phong Maple...',
    price: 360000,
  },
  {
    id: 26,
    name: 'Táo đỏ hữu cơ AmaVie Foods 450g',
    quantity: 41,
    sold: 0,
    isHot: false,
    isNew: false,
    rating: 4.5,
    image: '/images/assets/product-26.jpg',
    category: 'do-kho',
    to: '/',
    desc: 'Thành phần: 100% táo đỏ khô hữu cơ. Táo đỏ được người Trung Quốc ví là loại quả đến từ thiên đường. Từ xa xưa trong Đông Y, Táo đỏ luôn được xem là một vị...',
    price: 195000,
    discount: 5,
  },
  {
    id: 27,
    name: 'Bột Protein Từ Đậu Hữu Cơ 250gr',
    quantity: 82,
    sold: 0,
    isHot: false,
    isNew: false,
    rating: 2,
    image: '/images/assets/product-27.jpg',
    category: 'do-kho',
    to: '/',
    desc: 'Sản phẩm đạt chứng nhận hữu cơ Châu Âu được nhập khẩu trực tiếp từ Tây Ban Nha An toàn sử dụng cho người lớn và trẻ em trên 1 tuổi',
    price: 289000,
    discount: 7,
  },
];
