import { ProductType } from 'src/types/product';

export const bestSellsData: ProductType[] = [
  {
    id: 6,
    name: 'Nạc nọng giòn An Mộc 1kg',
    isHot: false,
    isNew: true,
    rating: 4.5,
    image: 'images/assets/product-6.jpg',
    category: 'thit-ca',
    to: '/',
    desc: '🌈Với quyết tâm thực hiện mô hình SẠCH TỪ TRANG TRẠI ĐẾN BÀN ĂN, thịt heo An Mộc luôn đảm bảo là thịt sạch tốt nhất cho sự lựa chọn của gia đình bạn. Là chuỗi trang trại..',
    price: 320000,
    quantity: 10,
    sold: 0,
  },
  {
    id: 11,
    name: 'Táo Juliet Hữu Cơ',
    isHot: false,
    isNew: false,
    rating: 4.5,
    image: 'images/assets/product-11.png',
    category: 'trai-cay',
    to: '/',
    desc: ' Dòng Táo hữu cơ của Miền Nam nước Pháp luôn được khách của Organic Mart đợi mong bởi ngoài yếu tố organic thì táo Juliet thật sự ngon giòn tan, ngọt lịm, rất cứng trái chứ không bị xốp bở',
    price: 139000,
    quantity: 10,
    sold: 0,
  },

  {
    id: 21,
    name: 'Mứt nam việt quất hữu cơ 320g Sottolestelle Organic Blueberrie Jam',
    isHot: false,
    isNew: false,
    rating: 4.5,
    image: 'images/assets/product-21.png',
    category: 'do-kho',
    to: '/',
    desc: 'Xuất xứ : Sottolestelle –Ý Shelf Life : 36 tháng kể từ ngày sản xuất Chứng nhận hữu cơ Châu Âu Non GMO Vegan ...',
    price: 115000,
    quantity: 10,
    sold: 0,
  },
  {
    id: 22,
    name: 'Mận An Phước',
    isHot: false,
    isNew: false,
    rating: 4.5,
    image: 'images/assets/product-22.jpg',
    category: 'trai-cay',
    to: '/',
    desc: 'Mận An Phước có vỏ màu đỏ tím, có vân nhạt, tỏa mùi thơm nhẹ. Mận được chăm sóc, chọn lọc kỹ càng từng trái, đảm bảo thơm ngon đúng chuẩn.',
    price: 63000,
    quantity: 10,
    sold: 0,
  },

  {
    id: 24,
    name: 'Kiwi vàng NewZealand 1kg',
    isHot: false,
    isNew: true,
    rating: 4.5,
    image: 'images/assets/product-25.jpg',
    category: 'trai-cay',
    to: '/',
    desc: 'Kiwi của Newzealand ngon số 1 thế giới. Toàn bộ quy trình từ trồng, chăm bón đến thu, hái, vận chuyển đều được chính phủ Newzealand kiểm soát rất chặt chẽ để đảm bảo trái Kiwi Newzealand',
    price: 179000,
    quantity: 10,
    sold: 0,
    discount: 10,
  },
  {
    id: 25,
    name: 'Siro Lá Phong Maple Syrup Hữu Cơ Radiant Code 250ml',
    isHot: false,
    isNew: false,
    rating: 4.5,
    image: 'images/assets/product-25.jpg',
    category: 'do-kho',
    to: '/',
    desc: 'Đạt chứng nhận hữu cơ BioGro của New Zealand Non - GMO, không chất bảo quản Không pha tạp chất, hóa chất độc hại Nhập khẩu từ Malaysia An toàn khi sử dụng Siro Lá Phong Maple...',
    price: 360000,
    quantity: 10,
    sold: 0,
  },
  {
    id: 6,
    name: 'Nạc nọng giòn An Mộc 1kg',
    isHot: false,
    isNew: true,
    rating: 4.5,
    image: 'images/assets/product-6.jpg',
    category: 'thit-ca',
    to: '/',
    desc: '🌈Với quyết tâm thực hiện mô hình SẠCH TỪ TRANG TRẠI ĐẾN BÀN ĂN, thịt heo An Mộc luôn đảm bảo là thịt sạch tốt nhất cho sự lựa chọn của gia đình bạn. Là chuỗi trang trại..',
    price: 320000,
    quantity: 10,
    sold: 0,
  },
  {
    id: 7,
    name: 'Cherry đỏ - size 9 1kg',
    isHot: false,
    isNew: false,
    rating: 3.5,
    image: 'images/assets/product-7.jpg',
    category: 'trai-cay',
    to: '/',
    desc: 'Nhập khẩu đường máy bay (Air). Hàng đầu mùa rất tươi, cuốn xanh. Mọng nước, trái chín đậm vị, trái xanh cứng trái. Đầu mùa vị ngọt chua...',
    price: 0,
    quantity: 10,
    sold: 0,
  },
  {
    id: 8,
    name: 'Tỏi tím Organic 200gr',
    isHot: true,
    isNew: false,
    rating: 4.5,
    image: 'images/assets/product-8.png',
    category: 'rau-cu',
    to: '/',
    desc: 'Trong thành phần của tỏi có chứa nhiều chất kháng sinh allicin giúp chống lại các virút gây bệnh, tăng sức đề kháng cho cơ thể. Tinh dầu chiết xuất từ tỏi giàu glucogen và aliin, fitonxit có...',
    price: 41500,
    quantity: 10,
    sold: 0,
  },
  {
    id: 27,
    name: 'Bột Protein Từ Đậu Hữu Cơ 250gr',
    isHot: false,
    isNew: false,
    rating: 2,
    image: 'images/assets/product-27.jpg',
    category: 'do-kho',
    to: '/',
    desc: 'Sản phẩm đạt chứng nhận hữu cơ Châu Âu được nhập khẩu trực tiếp từ Tây Ban Nha An toàn sử dụng cho người lớn và trẻ em trên 1 tuổi',
    price: 289000,
    quantity: 10,
    sold: 0,
    discount: 7,
  },
];
